#This file is used for install 
#required packages in harverst serever

#team-number:ccc-team16
#HongZhen Xie: 773383
#Dong Gao: 795622
#NanJiang Li: 741524
#KaiLe Wei: 812381
#Chuang Ying: 844566

- hosts: harverstServer
  become: yes
  become_user: root
  tasks:
  - name: Deployment of harvestServer
    shell: |
     apt-get update
     apt-get install -y python3-pip
     pip3 install tweepy 
     pip3 install couchdb 
     pip3 install simplejson 
     pip3 install regex 
     pip3 install vadersentiment
     pip3 install nltk 
    

     
      